### ISSUE TITLE
Chrome: Could not render he, see the console

### ISSUE THREAD

**Issue by karpy47** [scottie1984/swagger-ui-express#330]
**Using:** 
Win11, Chrome 109.0.5414.12

**Description:**
Some (to me) unknown JS-error. It used to work 2-3 months ago, and it works in Opera now. Json validated in swagger editor.

**I get this error in Chrome:**
Could not render he, see the console

**Console shows:**
TypeError: Need a string, to fetch a component. Was given a undefined
react_devtools_backend.js:4012
    at root-injects.jsx:91:11
    at r (memoize.js:62:23)
    at he.getLayout (app.jsx:9:23)
    at he.render (app.jsx:14:25)
    at Hi (react-dom.production.min.js:187:188)
    at Wi (react-dom.production.min.js:186:173)
    at Ks (react-dom.production.min.js:269:427)
    at Il (react-dom.production.min.js:250:347)
    at Ol (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)

TypeError: Need a string, to fetch a component. Was given a undefined
error-boundary.jsx:18 
    at root-injects.jsx:91:11
    at r (memoize.js:62:23)
    at he.getLayout (app.jsx:9:23)
    at he.render (app.jsx:14:25)
    at Hi (react-dom.production.min.js:187:188)
    at Wi (react-dom.production.min.js:186:173)
    at Ks (react-dom.production.min.js:269:427)
    at Il (react-dom.production.min.js:250:347)
    at Ol (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138) 

**Chrome has a suggestion:**
Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.
1 Source:
prepareInjection.js:1

**Comment by karpy47** [comment]
Seems like it was a json parsing error after all.
