### ISSUE TITLE
Uncaught ReferenceError: SwaggerUIBundle is not defined at window.onload with SwaggerUI on typescript

### ISSUE THREAD

**Issue by ag2byte** [scottie1984/swagger-ui-express#339]
I am trying to create documentation using `swagger-ui-express` and `swagger-jsdoc` as follows:
```ts 
import swaggerJsDoc from 'swagger-jsdoc';
import swaggerUi from 'swagger-ui-express';

const options: swaggerJsDoc.Options={
    definition:
    {
        openapi: '3.0.0',
        info: {
            title: 'API',   
            version: '1.0.0',
            description: 'API',
        },
        servers: [ {
                url: 'http://localhost:3000},],},
    apis: ['./src/api/**/*.ts'],
  }

const specs = swaggerJsDoc(options);

 app.use('/api-docs',swaggerUi.serve,swaggerUi.setup(specs));
    app.get('/api-docs.json',(req:Request,res:Response)=>{
        res.setHeader('Content-Type','application/json');
        res.send(specs);
    }
    )
```

While running I get the following issue on console: 

```
Uncaught SyntaxError: Unexpected token '<' (at swagger-ui-bundle.js:3:1)
swagger-ui-standalone-preset.js:3 
Uncaught SyntaxError: Unexpected token '<' (at swagger-ui-standalone-preset.js:3:1)
Uncaught ReferenceError: SwaggerUIBundle is not defined
    at window.onload
```

Is this issue related to any missing dependency or is this a bug?

**Comment by Emil21** [comment]
I'm facing the same issue. 
also getting http 502 error for bundle js call  '...../swagger-ui-bundle.js'.
Couple of times the UI loaded for me but then after that was always getting the above error.

I think this has something to do with the configurations. Because the issue doesn't appear for me in local and one of the environment , but only in my production env where certain things like load balancer etc are implemented.

**Comment by ag2byte** [comment]
Seems this issue exists when using webpack to configure the project. I  tried in a different react app built from scratch and it was working fine.

**Comment by Emil21** [comment]
@ag2byte I doubt it has something to do with webpack. Cz for me,  app is configured with webpack across all my environments., but I face this issue only in my prod env where these load balancer and stuffs are present

**Comment by YUEJINYUAN** [comment]
webpack need external swagger module,and you need keep path in webpack.config.js

```
optimization: {
    // minimize: true,
    minimizer: [
      new TerserPlugin({
        extractComments: { // keep same path with index.js => swaggerOptions.api
          condition: /^\**!|@swagger/i,
          filename: (fileData) => {
            // The "fileData" argument contains object with "filename", "basename", "query" and "hash"
            return './controller/swaggerComments.js';
          },
        },
      }),
    ],
  },

```

**Comment by jcjpsa** [comment]
> webpack need external swagger module,and you need keep path in webpack.config.js
> 
> ```
> optimization: {
>     // minimize: true,
>     minimizer: [
>       new TerserPlugin({
>         extractComments: { // keep same path with index.js => swaggerOptions.api
>           condition: /^\**!|@swagger/i,
>           filename: (fileData) => {
>             // The "fileData" argument contains object with "filename", "basename", "query" and "hash"
>             return './controller/swaggerComments.js';
>           },
>         },
>       }),
>     ],
>   },
> ```

Tried your solution but still throws an error for me, I even tried to load the `petstore` on the official documentation itself.

**Comment by i3i2uno** [comment]
This fixed it for me: https://stackoverflow.com/a/63048697/830403

**Comment by svinci121** [comment]
Hi, I'm not using webpack, but I'm having the same issue, it works locally but, when deployed it shows the following message. 
![Screenshot 2024-06-20 at 5 18 22 PM (2)](https://github.com/scottie1984/swagger-ui-express/assets/58568481/26588583-9d30-49ce-951e-ebea864d20ed)

I have it set up like:
  const swaggerDocument = YAML.load(path.join(__dirname, 'swagger.yaml'));
  const options = {}
  
  app.use('/api-docs',
    swaggerUi.serveFiles(swaggerDocument, options),
    swaggerUi.setup(swaggerDocument)
  );
  
  all other routes and middleware are below and I'm compiling with:
  
  ```
   "build": "rm -rf dist && tsc && cp swagger.yaml dist",
    "prestart": "NODE_OPTIONS=--openssl-legacy-provider npm run build",
    "start": "NODE_OPTIONS=--openssl-legacy-provider node ./dist/index.js",
    ```

**Comment by amunim** [comment]
@svinci121 you find a solution?

**Comment by robertoDCJ** [comment]
I have an express project that is also returning these errors in the console, but only in production, locally it works correctly

**Comment by andersonfernandes** [comment]
I faced the same problem while trying to build the code with esbuild and could solve it by adding `swagger-ui-express` as external using the flag: `--external:swagger-ui-express`.

Here is the complete build comman of my project:
```bash
esbuild src/index.ts --bundle --platform=node --outfile=dist/index.js --external:express --external:cors --external:swagger-ui-express,

```

**Comment by Edwin-WB-Li** [comment]
> Hi, I'm not using webpack, but I'm having the same issue, it works locally but, when deployed it shows the following message. ![Screenshot 2024-06-20 at 5 18 22 PM (2)](https://private-user-images.githubusercontent.com/58568481/341568015-26588583-9d30-49ce-951e-ebea864d20ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NTg0NjMsIm5iZiI6MTcyODk1ODE2MywicGF0aCI6Ii81ODU2ODQ4MS8zNDE1NjgwMTUtMjY1ODg1ODMtOWQzMC00OWNlLTk1MWUtZWJlYTg2NGQyMGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDAyMDkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxOWU0MDIyY2ViZGQxM2QyODJhYTBlMWMwYTE3ODMyNDNhYWQwOGM4ZTg2M2Q5NDg5NDUzZDVkNDhmZTJkYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.C7pgkj82RjgZyke3Dz_8E024p8weJz9PrreLNaf6q7o)
> 
> I have it set up like: const swaggerDocument = YAML.load(path.join(__dirname, 'swagger.yaml')); const options = {}
> 
> app.use('/api-docs', swaggerUi.serveFiles(swaggerDocument, options), swaggerUi.setup(swaggerDocument) );
> 
> all other routes and middleware are below and I'm compiling with:
> 
> ```
>  "build": "rm -rf dist && tsc && cp swagger.yaml dist",
>   "prestart": "NODE_OPTIONS=--openssl-legacy-provider npm run build",
>   "start": "NODE_OPTIONS=--openssl-legacy-provider node ./dist/index.js",
>   ```
> ```

Excuse me, have you solved this problem

**Comment by azegas** [comment]
> While running I get the following issue on console:
> 
> ```
> Uncaught SyntaxError: Unexpected token '<' (at swagger-ui-bundle.js:3:1)
> swagger-ui-standalone-preset.js:3 
> Uncaught SyntaxError: Unexpected token '<' (at swagger-ui-standalone-preset.js:3:1)
> Uncaught ReferenceError: SwaggerUIBundle is not defined
>     at window.onload
> ```

I did not have this issue when running project locally, but when I deployed it to vercel - I simply had a blank screen, no resources were loaded where swagger ui should be:

![image](https://github.com/user-attachments/assets/9fc4ca87-8b56-413a-a934-04301329dbf6)

But I found a workaround that has fixed my issue, had to edit vercel config:

![image](https://github.com/user-attachments/assets/137a6ba9-b9e6-4d79-8772-6cb1d9d407ec)

Simply told vercel to take the needed swagger files from node_modules and then it works:

![image](https://github.com/user-attachments/assets/8d925497-8c16-4f73-8dc1-884c671277ba)

**Comment by billysm23** [comment]
> > While running I get the following issue on console:
> > ```
> > Uncaught SyntaxError: Unexpected token '<' (at swagger-ui-bundle.js:3:1)
> > swagger-ui-standalone-preset.js:3 
> > Uncaught SyntaxError: Unexpected token '<' (at swagger-ui-standalone-preset.js:3:1)
> > Uncaught ReferenceError: SwaggerUIBundle is not defined
> >     at window.onload
> > ```
> 
> I did not have this issue when running project locally, but when I deployed it to vercel - I simply had a blank screen, no resources were loaded where swagger ui should be:
> 
> ![image](https://private-user-images.githubusercontent.com/78803192/388625459-9fc4ca87-8b56-413a-a934-04301329dbf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MDc3NjYsIm5iZiI6MTczMjUwNzQ2NiwicGF0aCI6Ii83ODgwMzE5Mi8zODg2MjU0NTktOWZjNGNhODctOGI1Ni00MTNhLWE5MzQtMDQzMDEzMjlkYmY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA0MDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjYjdkNjA5MmI3YWNhYzViNzk2NjA1N2I1YzhmZDU3ZDlhODU3ZTlkOWM3MTAxYTRhZTg4YzIwZTFmYzAxNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1IAtO4PGVy-LziXTZJhk23rXJWr8yqz4yrrrTyH0q1o)
> 
> But I found a workaround that has fixed my issue, had to edit vercel config:
> 
> ![image](https://private-user-images.githubusercontent.com/78803192/388623375-137a6ba9-b9e6-4d79-8772-6cb1d9d407ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MDc3NjYsIm5iZiI6MTczMjUwNzQ2NiwicGF0aCI6Ii83ODgwMzE5Mi8zODg2MjMzNzUtMTM3YTZiYTktYjllNi00ZDc5LTg3NzItNmNiMWQ5ZDQwN2VjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA0MDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczY2MxYzY0ZGE0YzQ4N2RiMzNkYWRkMjY2MWYzYWE1YmEzZDhlMjQwNmVjYTlkMzI3YzQzYmIxNTc4MTc4OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oJm23F5KlXebs9w2luQzV4ViiWstThp-SKg_0Br--Bw)
> 
> Simply told vercel to take the needed swagger files from node_modules and then it works:
> 
> ![image](https://private-user-images.githubusercontent.com/78803192/388625134-8d925497-8c16-4f73-8dc1-884c671277ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MDc3NjYsIm5iZiI6MTczMjUwNzQ2NiwicGF0aCI6Ii83ODgwMzE5Mi8zODg2MjUxMzQtOGQ5MjU0OTctOGMxNi00ZjczLThkYzEtODg0YzY3MTI3N2JhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA0MDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMmExZWU4ZjhiOTI0MjQ3YWE0YmQ3MmRjYjNlM2I0OWYwZWIxNTA0MTc3MzVkOTY0MWZmZWZjY2EyMTYzN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KnMDAW1eZZDHX4JR-l_VYc7TTPkxvoTVOHr9n3cnvCQ)

thank you so much brother

**Comment by nyomanyudisdeveloper** [comment]
> > While running I get the following issue on console:
> > ```
> > Uncaught SyntaxError: Unexpected token '<' (at swagger-ui-bundle.js:3:1)
> > swagger-ui-standalone-preset.js:3 
> > Uncaught SyntaxError: Unexpected token '<' (at swagger-ui-standalone-preset.js:3:1)
> > Uncaught ReferenceError: SwaggerUIBundle is not defined
> >     at window.onload
> > ```
> 
> I did not have this issue when running project locally, but when I deployed it to vercel - I simply had a blank screen, no resources were loaded where swagger ui should be:
> 
> ![image](https://private-user-images.githubusercontent.com/78803192/388625459-9fc4ca87-8b56-413a-a934-04301329dbf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1Njk1MzAsIm5iZiI6MTczMzU2OTIzMCwicGF0aCI6Ii83ODgwMzE5Mi8zODg2MjU0NTktOWZjNGNhODctOGI1Ni00MTNhLWE5MzQtMDQzMDEzMjlkYmY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDExMDAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NGRhYmM2MDQ1NWNmYzNiZjUwMzhlOGVlNjU3N2NmMzg3NDU2MThlMzhkN2I3ZjJhZTBkMGZmZDIxMGEyYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nqDfsohG7n0HzcjwIVOpL1QTGYhbvQWQKwh0q6JheqE)
> 
> But I found a workaround that has fixed my issue, had to edit vercel config:
> 
> ![image](https://private-user-images.githubusercontent.com/78803192/388623375-137a6ba9-b9e6-4d79-8772-6cb1d9d407ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1Njk1MzAsIm5iZiI6MTczMzU2OTIzMCwicGF0aCI6Ii83ODgwMzE5Mi8zODg2MjMzNzUtMTM3YTZiYTktYjllNi00ZDc5LTg3NzItNmNiMWQ5ZDQwN2VjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDExMDAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzODA2M2Y1ZGMwYWRlM2Y3N2U4YWI3ZTY3ODAyYzI3ZTNkMjM3ZDZlYzkwOGY4ODA5OWRjYjlmYTRiYmMzMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MVJDt3dbrW9z6otR48NiLjjTwnp0R483MFuMsTwrR_I)
> 
> Simply told vercel to take the needed swagger files from node_modules and then it works:
> 
> ![image](https://private-user-images.githubusercontent.com/78803192/388625134-8d925497-8c16-4f73-8dc1-884c671277ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1Njk1MzAsIm5iZiI6MTczMzU2OTIzMCwicGF0aCI6Ii83ODgwMzE5Mi8zODg2MjUxMzQtOGQ5MjU0OTctOGMxNi00ZjczLThkYzEtODg0YzY3MTI3N2JhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDExMDAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NzVmNzIwMjA0M2I0ZDE3ZTM3NmY2NjdjNzdiYzk5OGQyNTI4Y2VjMDMxYjNlNmU3MjIyOGMxNmUyZjhmODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ehmwh2mhD7ZbYM2ctSmZj0FfBDibdqh7pW9g5ndqg-Y)

Thank you so much, i dont know what to do without you.

**Comment by josesantiz-dev** [comment]
> > Mientras ejecuto, aparece el siguiente problema en la consola:
> > ```
> > Uncaught SyntaxError: Unexpected token '<' (at swagger-ui-bundle.js:3:1)
> > swagger-ui-standalone-preset.js:3 
> > Uncaught SyntaxError: Unexpected token '<' (at swagger-ui-standalone-preset.js:3:1)
> > Uncaught ReferenceError: SwaggerUIBundle is not defined
> >     at window.onload
> > ```
> 
> No tuve este problema al ejecutar el proyecto localmente, pero cuando lo implementé en Vercel, simplemente tuve una pantalla en blanco, no se cargaron recursos donde debería estar la interfaz de usuario de Swagger:
> 
> ![image](https://github.com/user-attachments/assets/9fc4ca87-8b56-413a-a934-04301329dbf6)
> 
> Pero encontré una solución alternativa que solucionó mi problema, tuve que editar la configuración de Vercel:
> 
> ![image](https://github.com/user-attachments/assets/137a6ba9-b9e6-4d79-8772-6cb1d9d407ec)
> 
> Simplemente le dije a vercel que tomara los archivos swagger necesarios de node_modules y luego funciona:
> 
> ![image](https://github.com/user-attachments/assets/8d925497-8c16-4f73-8dc1-884c671277ba)

Thanks

**Comment by Chernik1991** [comment]
vercel.json
{
  "version": 2,
  "$schema": "https://openapi.vercel.sh/vercel.json",
  "name": "bloggerPlatform",
  "buildCommand": "pnpm run build",
  "builds": [
    { "src": "src/index.ts", "use": "@vercel/node",
      "config": {
        "includeFiles":["./node_modules/**","src/**/*.yml"]
      }
    }
  ],
  "routes": [
    { "src": "/(.*)", "dest": "src/index.ts"}
  ]
}

and add in package.json  "build": "tsc && cpx \"src/**/*.yml\" dist", end install cpx

**Comment by fabioramos-02** [comment]
Para resolver o erro ReferenceError: SwaggerUIBundle is not defined que você está enfrentando, é importante garantir que o Swagger UI e seus arquivos associados (como o swagger-ui-bundle.js, swagger-ui-standalone-preset.js e outros recursos) estejam sendo carregados corretamente.

O erro ocorre quando o Swagger UI não consegue encontrar os arquivos necessários ou o Swagger UI não é inicializado corretamente. Quando você usa o CDN para os arquivos do Swagger UI, você precisa garantir que eles sejam carregados e inicializados corretamente na página.

Aqui está uma explicação simples e didática para resolver esse erro:

1. Problema: O Swagger UI não está sendo carregado corretamente

Ao carregar o Swagger UI usando CDN, você precisa garantir que todos os scripts necessários estejam carregados antes de tentar inicializar o SwaggerUI. No seu código, você está passando os arquivos JavaScript diretamente como URLs para o Swagger, mas o Swagger não está sendo inicializado corretamente.

2. Solução: Incluir o Script do SwaggerUI e Corrigir a Inicialização

O erro de "SwaggerUIBundle is not defined" ocorre porque o script do Swagger UI não foi carregado ou não foi inicializado corretamente antes de tentar configurar o Swagger UI na página.

// Configuração do Swagger UI com CDN customizado
const swaggerOptions = {
  customCss: '.swagger-ui .topbar { display: none }',
  customSiteTitle: "API de Cálculo de Score",
  customCssUrl: 'https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.15.5/swagger-ui.min.css',
  customJs: [
    'https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.15.5/swagger-ui-bundle.min.js',
    'https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.15.5/swagger-ui-standalone-preset.min.js'
  ],
  swaggerOptions: {
    url: '/swagger.json',
  }
};

Uso do customJs: Ao usar os arquivos do Swagger UI através de CDN, é importante garantir que o script swagger-ui-bundle.min.js seja carregado primeiro, seguido do script swagger-ui-standalone-preset.min.js. Estes são os arquivos responsáveis por inicializar o Swagger UI corretamente.

Garantir a inicialização correta: A propriedade swaggerOptions dentro de swaggerUi.setup garante que a documentação da API seja carregada corretamente com base no arquivo swagger.json.
