### ISSUE TITLE
totally does not load on production

### ISSUE THREAD

**Issue by m0x61h0x64i** [scottie1984/swagger-ui-express#358]
Hi, yesterday I could load my swagger docs using its URL, but today when i committed my new changes it no longer loads my swagger docs on production, but on the development everything works fine.

my last commit was on Jul 3, at that moment until new commit which was today i dint have problem because yesterday docs loaded fine

after i pushed my new commit today, swagger does not load on production, i can see some errors in the console :

![image](https://github.com/scottie1984/swagger-ui-express/assets/109550653/37967684-1d9b-42a7-b165-09fe84a57d00)
```
swagger-ui-bundle.js:3 Uncaught SyntaxError: Unexpected token '<' (at swagger-ui-bundle.js:3:1)
swagger-ui-standalone-preset.js:3 Uncaught SyntaxError: Unexpected token '<' (at swagger-ui-standalone-preset.js:3:1)
DevTools failed to load source map: Could not load content for https://*/api-docs/swagger-ui.css.map: Unexpected token '<', "
<!-- HTML "... is not valid JSON
swagger-ui-init.js:58 Uncaught ReferenceError: SwaggerUIBundle is not defined
    at window.onload (swagger-ui-init.js:58:7)
```

I have tried disabling all routes, cause i have written new routes and docs, but that didnt help.

now this is my localhost : 
![image](https://github.com/scottie1984/swagger-ui-express/assets/109550653/26607df6-28c0-4bf6-8621-4c2e4cbc7a58)

and this is my production swagger : 
![image](https://github.com/scottie1984/swagger-ui-express/assets/109550653/c30aff09-bd85-4c49-99da-800082584cb0)

swagger-jsdoc version : 6.2.8
swagger-ui-express version : 5.0.0
hosting: vercel

my problem wont be my code, i have checked my Jul 3 commit and it was the same code as it was and also i removed the routes to test if it can be loaded or not but it didnt load swagger doc on production.

**Comment by rohithSSV** [comment]
![Screenshot 2023-09-06 110335](https://github.com/scottie1984/swagger-ui-express/assets/141988584/647946f3-6401-4cf1-a5c8-980c12827966)
Can we enable swagger UI in HTTP also

**Comment by urvashichhabra** [comment]
Facing same issue as @m0x61h0x64i.

**Comment by urvashichhabra** [comment]
Fixed this issue with a workaround. Changes made in esbuild.config.js. 

`const { build } = require('esbuild');
const { copy } = require('esbuild-plugin-copy');

build({
	entryPoints: ['index.ts'],
	outdir: 'build',  // destination folder 
	sourcemap: 'inline',
	platform: 'node',
	bundle: true,
	plugins: [
		copy({
			assets: [
				{
					from: ['./node_modules/swagger-ui-dist/swagger-ui-bundle.js'],
					to: 'build/SwaggerUIBundle.js',   // in destination folder
				},
				{
					from: [
						'./node_modules/swagger-ui-dist/swagger-ui-standalone-preset.js',
					],
					to: 'build/SwaggerUIStandalonePreset.js',  // in destination folder
				},
			],
		}),
	],
}).catch(() => process.exit(1)); // Exit with an error code on build failure`
