### ISSUE TITLE
Cannot find indexTemplate.html

### ISSUE THREAD

**Issue by mattmahn** [scottie1984/swagger-ui-express#42]
I'm using this along with swagger-jsdoc to document my Express endpoints. When I try to start the app, I get the following error:
```
fs.js:663
  return binding.open(pathModule.toNamespacedPath(path),
                 ^

Error: ENOENT: no such file or directory, open '//indexTemplate.html'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
    at Object.setup (webpack-internal:///197:16:16)
    at eval (webpack-internal:///196:70:82)
    at Object.<anonymous> (/home/matt/code/express-api-documentation/.dist/index.js:2354:1)
    at __webpack_require__ (/home/matt/code/express-api-documentation/.dist/index.js:20:30)
    at eval (webpack-internal:///120:19:16)
    at Object.<anonymous> (/home/matt/code/express-api-documentation/.dist/index.js:1473:1)
    at __webpack_require__ (/home/matt/code/express-api-documentation/.dist/index.js:20:30)
    at /home/matt/code/express-api-documentation/.dist/index.js:63:18
```

There seems to be something weird causing it to look for `//indexTemplate.html` instead of some relative/absolute path (i.e., not `//foo`).
I'm setting up swagger-ui-express like this:  ([permalink to file in project](https://github.com/mattmahn/express-api-documentation/blob/559bef87bc844ab7f7224f6acc4f3772e1a9d2a3/src/swagger.js))
```js
import express from 'express'
import path from 'path'
import swaggerUI from 'swagger-ui-express'
import swaggerJsDoc from 'swagger-jsdoc'
import npmMeta from '../package.json'

const router = express.Router()

const swaggerSpec = swaggerJsDoc({
  swaggerDefinition: {
    info: {
      title: 'Library',
      description: 'Example documentation of Express API',
      version: npmMeta.version,
      license: {
        name: 'Unlicense',
        url: 'http://unlicense.org/UNLICENSE'
      }
    }
  },
  apis: [ `./api/*` ]
})
router.get('/spec.json', (req, res) => {
  res.send(swaggerSpec)
})
router.use('/docs', swaggerUI.serve, swaggerUI.setup(swaggerSpec))

export default router;
```
I then use that exported router like so: ([permalink with context](https://github.com/mattmahn/express-api-documentation/blob/559bef87bc844ab7f7224f6acc4f3772e1a9d2a3/src/index.js#L17))
```js
import express from 'express'
import swagger from './swagger'

const app = express()
// snip
app.use('/swagger', swagger)
// snip
```

[Full source](https://github.com/mattmahn/express-api-documentation/tree/swagger)

**Comment by scottie1984** [comment]
The issue is due to webpack, the module serves the swagger ui client files from within the module therefore it won't work with any bundling.

**Comment by mattmahn** [comment]
Closing, as not bundling is working as expected
